### PR TITLE
Add heart rate measument service

### PR DESCRIPTION
**Pull request by hotchpotch**
I add heart rate measument service.

- https://developer.bluetooth.org/gatt/services/Pages/ServiceViewer.aspx?u=org.bluetooth.service.heart_rate.xml

If you are OK, please merge this.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@hotchpotch looks good!

I have a few minor suggestions though:

1) I think it would be better if ```this.onMeasumentChangeBinded = this.onMeasumentChange.bind(this);``` was moved from the constructor to ```notifyMeasument``` this way the user does not have to call ```NobleDevice.HeartRateMeasumentService.call(this);``` from their constructor.

2) I think it's time for an ```examples``` folder in the root, then ```test-hrm.js``` (as well as ```test.js```) can be moved there and also renamed.

What do you think? I'm happy to make the above changes if you do not have time to make them.

**Comment by hotchpotch** [comment]
@sandeepmistry 

Thank you for your advice!
I applied it.

And, your products (noble, noble-device, node-bluetooth-hci-socket...) are very cool.
Thanks!

**Comment by sandeepmistry** [comment]
@hotchpotch thanks!

I've made a few minor changes https://github.com/sandeepmistry/noble-device/commit/44c06f31fe7e385b4ea64d967b64e3794503dbd9.

**Comment by hotchpotch** [comment]
Thanks !

**Comment by sandeepmistry** [comment]
Version 1.3.0 has also been published to npm with your changes :)

**Pull request merged**
